import type { ThemeId, ThemeTokens } from '../types'

export const themes: Record<ThemeId, ThemeTokens> = {
  burgundy: {
    id: 'burgundy',
    name: 'Burgundy',
    primary: '#6b1d2a',
    secondary: '#8e2a3a',
    background: '#f6f0e6',
    surface: '#fffaf3',
    text: '#2c1a16',
    muted: '#8a7468',
    accent: '#4e6a4a',
    gold: '#c9a24d',
  },
  red: {
    id: 'red',
    name: 'Red',
    primary: '#9b2335',
    secondary: '#c43b4b',
    background: '#f8f1e8',
    surface: '#fffdf8',
    text: '#2a1614',
    muted: '#8c736c',
    accent: '#5b6e4e',
    gold: '#d4af67',
  },
  green: {
    id: 'green',
    name: 'Green',
    primary: '#3f5a3c',
    secondary: '#5c7a52',
    background: '#f3f0e6',
    surface: '#fbfaf4',
    text: '#1f2a1c',
    muted: '#6e7568',
    accent: '#8b3a3a',
    gold: '#c2a15a',
  },
  gold: {
    id: 'gold',
    name: 'Gold',
    primary: '#8a6a2f',
    secondary: '#c4a35a',
    background: '#f7f2e6',
    surface: '#fffaf0',
    text: '#2b2214',
    muted: '#84765c',
    accent: '#6b2b2b',
    gold: '#d6b36a',
  },
  pink: {
    id: 'pink',
    name: 'Pink',
    primary: '#8d4a5a',
    secondary: '#c77b8a',
    background: '#f8f0ee',
    surface: '#fff8f7',
    text: '#2c1b1e',
    muted: '#8a7174',
    accent: '#5e6b4e',
    gold: '#c9a66b',
  },
  beige: {
    id: 'beige',
    name: 'Beige',
    primary: '#6e5848',
    secondary: '#a08a74',
    background: '#f4eee4',
    surface: '#fbf7f0',
    text: '#2a2118',
    muted: '#7d7164',
    accent: '#6b2e2e',
    gold: '#c2a46a',
  },
}

export const templateOptions = [
  { id: 'template-01', name: 'Template 01 – Modern Red' },
  { id: 'template-02', name: 'Template 02 – Minimal Ivory' },
  { id: 'template-03', name: 'Template 03 – Vietnamese Traditional' },
  { id: 'template-04', name: 'Template 04 – Editorial' },
  { id: 'template-05', name: 'Template 05 – Floral' },
] as const
